package com.patterns.java;

/* THIS ENUM WILL BE USED TO REPRESENT THE FRAME COLORS
* OF ALL THE ACME BICYCLES */

public enum BikeColor {
    UNPAINTED, CHROME, BLACK, BLUE, RED, GREEN, ORANGE, GOLD
}
